server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: usuario-service3
          uri: lb://usuario-service3
          predicates:
            - Path=//usuario/**
        - id: clinica-service
          uri: lb://clinica-service
          predicates:
            - Path=//clinica/**
        - id: hospital-service
          uri: lb://hospital-service
          predicates:
            - Path=//hospital/**
